from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QScrollArea, QWidget, QListWidgetItem, QLabel
import sys


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()

        self.centralwidget = QWidget(self)

        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollAreaWidgetContents = QWidget()
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)

        self.label = QLabel(self.centralwidget)

        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1100, 750)
        self.setDocumentMode(False)
        self.setDockNestingEnabled(False)

        self.centralwidget.setObjectName("centralwidget")

        self.scrollArea.setGeometry(QtCore.QRect(100, 180, 361, 161))
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.listWidget.setGeometry(QtCore.QRect(0, 0, 361, 161))

        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(16)

        self.listWidget.setFont(font)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setObjectName("listWidget")

        for x in range(0, 8):
            self.listWidget.addItem(QListWidgetItem())

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.label.setGeometry(QtCore.QRect(180, 20, 731, 131))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 370, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 420, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        font.setItalic(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 630, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        font.setItalic(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 640, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        font.setItalic(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.ekgView = QtWidgets.QGraphicsView(self.centralwidget)
        self.ekgView.setGeometry(QtCore.QRect(530, 180, 461, 161))
        self.ekgView.setObjectName("ekgView")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(530, 370, 461, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 190, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 380, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionRelease = QtWidgets.QAction(self)
        self.actionRelease.setObjectName("actionRelease")
        self.actionInfo = QtWidgets.QAction(self)
        self.actionInfo.setObjectName("actionInfo")
        self.actionRelease_2 = QtWidgets.QAction(self)
        self.actionRelease_2.setObjectName("actionRelease_2")
        self.actionAuthors = QtWidgets.QAction(self)
        self.actionAuthors.setObjectName("actionAuthors")
        self.actionAdd_patient = QtWidgets.QAction(self)
        self.actionAdd_patient.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionAdd_patient.setObjectName("actionAdd_patient")
        self.menuFile.addAction(self.actionAdd_patient)
        self.menuAbout.addAction(self.actionInfo)
        self.menuAbout.addAction(self.actionRelease_2)
        self.menuAbout.addAction(self.actionAuthors)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "pacjent001"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "pacjent002"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "pacjent003"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "pacjent004"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "pacjent005"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "pacjent006"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "pacjent007"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "pacjent008"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Oprogramowanie do wczytywania oraz prezentacji wektrokardiogramu"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Myriad Pro Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:30px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Myriad Pro\'; font-style:italic; color:#4b4b4b;\">Wprowadź scieżkę pliku wraz z jego nazwą</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Wybierz plik"))
        self.pushButton_2.setText(_translate("MainWindow", "Zatwierdź"))
        self.pushButton_3.setText(_translate("MainWindow", "Zapisz"))
        self.label_2.setText(_translate("MainWindow", "EKG"))
        self.label_3.setText(_translate("MainWindow", "WEKTROKARDIOGRAM"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionRelease.setText(_translate("MainWindow", "Release"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionRelease_2.setText(_translate("MainWindow", "Release"))
        self.actionAuthors.setText(_translate("MainWindow", "Authors"))
        self.actionAdd_patient.setText(_translate("MainWindow", "Add patient"))
        self.actionAdd_patient.setShortcut(_translate("MainWindow", "Ctrl+N"))


app = QApplication(sys.argv)
ui = Ui_MainWindow()
ui.show()
sys.exit(app.exec())
